#!/usr/bin/env python3
"""Load a previously saved word list and cut selected words from audio."""

import sys
import os
import json
import subprocess


def display_words(words: list[dict]):
    print("\n" + "=" * 60)
    print(f"{'#':>3}  {'Arabic':<15} {'English':<20} {'Time':>12}  {'Conf':>5}")
    print("-" * 60)
    for i, w in enumerate(words):
        time_range = f"{w['start']:.1f}s-{w['end']:.1f}s"
        score = f"{w.get('score', 0):.0%}"
        print(f"{i:>3}  {w['word']:<15} {w.get('english', '?'):<20} {time_range:>12}  {score:>5}")
    print("=" * 60)


def cut_words(audio_path: str, words: list[dict], indices: list[int], output_dir: str):
    os.makedirs(output_dir, exist_ok=True)
    for idx in indices:
        w = words[idx]
        start = max(0, w["start"] - 0.05)
        duration = (w["end"] - w["start"]) + 0.1
        safe_name = w["word"].replace(" ", "_")
        out_file = os.path.join(output_dir, f"{idx:03d}_{safe_name}.wav")
        subprocess.run([
            "ffmpeg", "-y", "-i", audio_path,
            "-ss", str(start), "-t", str(duration),
            "-ar", "44100", "-ac", "1",
            out_file
        ], capture_output=True)
        print(f"  Cut: {w['word']} ({w.get('english', '?')}) -> {out_file}")
    print(f"\n{len(indices)} clips saved to {output_dir}/")


def parse_selection(selection: str, max_idx: int) -> list[int]:
    indices = []
    for part in selection.split(","):
        part = part.strip()
        if "-" in part:
            start, end = part.split("-", 1)
            indices.extend(range(int(start), int(end) + 1))
        elif part == "*":
            return list(range(max_idx + 1))
        elif part.isdigit():
            indices.append(int(part))
    return [i for i in indices if 0 <= i <= max_idx]


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python cut.py <words.json>")
        print("\nThe JSON file is generated by transcribe.py")
        sys.exit(1)

    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)

    audio_path = data["audio_path"]
    words = data["words"]

    display_words(words)

    print("\nEnter word numbers to cut (e.g. '0,3,5-10' or '*' for all, 'q' to quit):")
    selection = input("> ").strip()

    if selection.lower() == "q":
        sys.exit(0)

    indices = parse_selection(selection, len(words) - 1)
    if not indices:
        print("No valid selections.")
        sys.exit(0)

    output_dir = audio_path.rsplit(".", 1)[0] + "_clips"
    cut_words(audio_path, words, indices, output_dir)
